app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0' -P /dev/null
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:10
  ports:
    - "5432"